### ISSUE TITLE
实验不足

### ISSUE THREAD

**Issue by 779257747** [gersteinlab/MedAgents#2]
为什么实验结果没有与gpt4进行对比，是因为MC framework的推理能力并不如GPT4的zero-shot, zero-shot cot, few-shot,few-shot cot 和 few- shot cot + sc吗？
<img width="921" alt="image" src="https://github.com/gersteinlab/MedAgents/assets/63271390/e58f06bb-4a96-4668-af99-546e9a3418b8">

**Comment by Anni-Zou** [comment]
Thanks for your attention, we will include the experimental results of the GPT-4 baseline methods in the next revision.
