### ISSUE TITLE
What did you do for the evaluation? 

### ISSUE THREAD

**Issue by huangbhan** [gersteinlab/MedAgents#3]
hi,What did you do for the evaluation?

**Comment by tangxiangru** [comment]
We evaluate our MC framework on two benchmark datasets MedQA, MedMCQA, and PubMedQA, as well as six subtasks most relevant to the medical domain from MMLU datasets including anatomy, clinical knowledge, college medicine, medical genetics, professional medicine, and college biology

Those are all multi-choice question-answering datasets.

We have uploaded our dataset here: https://drive.google.com/file/d/11qNzDYIlimGGJ1fhQn2ux6w_rfFgJbyo/view?usp=sharing.
