### ISSUE TITLE
How long did it take you to do these evaluation?

### ISSUE THREAD

**Issue by hanrthu** [gersteinlab/MedAgents#4]
Hello, I am running MedAgents' code and find it slow to get one answer (One question takes about 2~3 minutes). So I wonder if there is any method to speed it up. And how do you evaluate your methods on those datasets? How much time did it take?

**Comment by tangxiangru** [comment]
If you use ChatGPT API calling it will be much slower. However, we are using Azure and we set up 300K TPM tokens per minute for gpt-35-turbo. It would be 30-50s per example.
